development:
  adapter: mysql2
  database: asian_fibro_dev
  username: root
  password: root

test:
  adapter: mysql2
  database: asian_fibro_test
  username: root
  password: root

production:
  adapter: mysql2
  database: asian_fibro_prod
  username: root
  password: root
